[package]
name = "cutr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.16"
common = { version = "0.1.0", path = "../common" }
csv = "1.3.0"
regex = "1.10.2"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.0.4"
rand = "0.8.5"
