[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = "3.1.6"
users = "0.11"
tabular = "0.2.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
